; content/data/manifest/blueprint.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/blueprint/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::blueprint:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::blueprint>
    :neutral>
      @define>
        2 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
