; content/data/manifest/building.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/building/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::building:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::building>
    :chord>
      @define>
        1 &texture array
        1.png &texture.0 set
    :neutral>
      @define>
        1 &texture array
        1.png &texture.0 set
