; content/data/manifest/deciduous.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/deciduous/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::deciduous:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::deciduous>
    :neutral>
      @define>
        7 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
        3.png &texture.2 set
        4.png &texture.3 set
        5.png &texture.4 set
        6.png &texture.5 set
        7.png &texture.6 set
