; content/data/manifest/fog.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/fog/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::fog:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::fog>
    :neutral>
      @define>
        16 &texture array
        1_1.png &texture.0 set
        1_2.png &texture.1 set
        1_3.png &texture.2 set
        1_4.png &texture.3 set
        1_5.png &texture.4 set
        1_6.png &texture.5 set
        1_7.png &texture.6 set
        1_8.png &texture.7 set
        1_9.png &texture.8 set
        1_10.png &texture.9 set
        1_11.png &texture.10 set
        1_12.png &texture.11 set
        1_13.png &texture.12 set
        1_14.png &texture.13 set
        1_15.png &texture.14 set
        1_16.png &texture.15 set
