; content/data/manifest/fountain.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/fountain/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::fountain:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::fountain>
    :chord>
      @define>
        2 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
    :chorus>
      @define>
        2 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
    :neutral>
      @define>
        2 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
    :original>
      @define>
        2 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
    :resonance>
      @define>
        2 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
