; content/data/manifest/requisite.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/requisite/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::requisite:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::requisite>
    :neutral>
      @define>
        53 &texture array
        1.png &texture.0 set
        1_1.png &texture.1 set
        1_2.png &texture.2 set
        1_3.png &texture.3 set
        1_4.png &texture.4 set
        1_5.png &texture.5 set
        1_6.png &texture.6 set
        1_7.png &texture.7 set
        1_8.png &texture.8 set
        1_9.png &texture.9 set
        1_10.png &texture.10 set
        1_11.png &texture.11 set
        2.png &texture.12 set
        2_1.png &texture.13 set
        3.png &texture.14 set
        3_1.png &texture.15 set
        3_2.png &texture.16 set
        3_3.png &texture.17 set
        3_4.png &texture.18 set
        3_5.png &texture.19 set
        4.png &texture.20 set
        4_1.png &texture.21 set
        5.png &texture.22 set
        5_1.png &texture.23 set
        5_2.png &texture.24 set
        5_3.png &texture.25 set
        5_4.png &texture.26 set
        5_5.png &texture.27 set
        5_6.png &texture.28 set
        5_7.png &texture.29 set
        5_8.png &texture.30 set
        5_9.png &texture.31 set
        5_10.png &texture.32 set
        5_11.png &texture.33 set
        5_12.png &texture.34 set
        5_13.png &texture.35 set
        5_14.png &texture.36 set
        5_15.png &texture.37 set
        5_16.png &texture.38 set
        6.png &texture.39 set
        6_1.png &texture.40 set
        7.png &texture.41 set
        8.png &texture.42 set
        9.png &texture.43 set
        10.png &texture.44 set
        11.png &texture.45 set
        12.png &texture.46 set
        13.png &texture.47 set
        14.png &texture.48 set
        15.png &texture.49 set
        16.png &texture.50 set
        17.png &texture.51 set
        18.png &texture.52 set
