; content/data/manifest/table_slab.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/table_slab/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::table_slab:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::table_slab>
    :chord>
      @define>
        1 &texture array
        1.png &texture.0 set
    :chorus>
      @define>
        1 &texture array
        1.png &texture.0 set
    :neutral>
      @define>
        1 &texture array
        1.png &texture.0 set
    :original>
      @define>
        1 &texture array
        1.png &texture.0 set
    :resonance>
      @define>
        1 &texture array
        1.png &texture.0 set
