; content/data/manifest/berry.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/berry/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::berry:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::berry>
    :neutral>
      @define>
        12 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
        3.png &texture.2 set
        4.png &texture.3 set
        5.png &texture.4 set
        6.png &texture.5 set
        7.png &texture.6 set
        8.png &texture.7 set
        9.png &texture.8 set
        10.png &texture.9 set
        11.png &texture.10 set
        12.png &texture.11 set
