; content/data/manifest/concrete.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/concrete/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::concrete:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::concrete>
    :chord>
      @define>
        1 &texture array
        1.png &texture.0 set
    :chorus>
      @define>
        1 &texture array
        1.png &texture.0 set
    :neutral>
      @define>
        1 &texture array
        1.png &texture.0 set
    :resonant>
      @define>
        1 &texture array
        1.png &texture.0 set
