; content/data/manifest/flora.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/flora/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::flora:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::flora>
    :neutral>
      @define>
        30 &texture array
        1_1.png &texture.0 set
        1_2.png &texture.1 set
        1_3.png &texture.2 set
        1_4.png &texture.3 set
        1_5.png &texture.4 set
        1_6.png &texture.5 set
        1_7.png &texture.6 set
        1_8.png &texture.7 set
        1_9.png &texture.8 set
        1_10.png &texture.9 set
        1_11.png &texture.10 set
        1_12.png &texture.11 set
        1_13.png &texture.12 set
        2_1.png &texture.13 set
        2_2.png &texture.14 set
        2_3.png &texture.15 set
        2_4.png &texture.16 set
        2_5.png &texture.17 set
        2_6.png &texture.18 set
        2_7.png &texture.19 set
        2_8.png &texture.20 set
        2_9.png &texture.21 set
        2_10.png &texture.22 set
        2_11.png &texture.23 set
        2_12.png &texture.24 set
        2_13.png &texture.25 set
        2_14.png &texture.26 set
        2_15.png &texture.27 set
        2_16.png &texture.28 set
        2_17.png &texture.29 set
