; content/data/manifest/soul_offline.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust/pixijs/public/textures/master/soul_offline/<faction>/.
; One :faction facet per subfolder; the texture array lists that folder's
; sprite files so $manifest::soul_offline:<faction>.texture.<i> resolves to a
; filename. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::soul_offline>
    :chord>
      @define>
        16 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
        3.png &texture.2 set
        4.png &texture.3 set
        5.png &texture.4 set
        6.png &texture.5 set
        7.png &texture.6 set
        8.png &texture.7 set
        9.png &texture.8 set
        10.png &texture.9 set
        11.png &texture.10 set
        12.png &texture.11 set
        13.png &texture.12 set
        14.png &texture.13 set
        15.png &texture.14 set
        16.png &texture.15 set
    :chorus>
      @define>
        16 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
        3.png &texture.2 set
        4.png &texture.3 set
        5.png &texture.4 set
        6.png &texture.5 set
        7.png &texture.6 set
        8.png &texture.7 set
        9.png &texture.8 set
        10.png &texture.9 set
        11.png &texture.10 set
        12.png &texture.11 set
        13.png &texture.12 set
        14.png &texture.13 set
        15.png &texture.14 set
        16.png &texture.15 set
    :resonance>
      @define>
        16 &texture array
        1.png &texture.0 set
        2.png &texture.1 set
        3.png &texture.2 set
        4.png &texture.3 set
        5.png &texture.4 set
        6.png &texture.5 set
        7.png &texture.6 set
        8.png &texture.7 set
        9.png &texture.8 set
        10.png &texture.9 set
        11.png &texture.10 set
        12.png &texture.11 set
        13.png &texture.12 set
        14.png &texture.13 set
        15.png &texture.14 set
        16.png &texture.15 set
