; content/data/asset/01.rd
; Asset packs — render config for sprite art. Each ::pack points at a manifest
; object via `$manifest::<obj> &object set` (the sprite files live in
; manifest/<obj>.rd, generated by `bin/art manifest`) and adds render params:
; `size` = native px; `scale` = a min/max envelope in HUNDREDTHS (biome-style
; 0..100, so `80 100` = 0.8..1.0); `anchor` = pivot `{x,y}` via `vec2` (`50 50` = center).
; Defaults (scale 100/100, anchor 50/50) are omitted. Cards put `$asset::<pack>`
; in an object slot; the renderer derefs &object -> manifest faction -> texture.
; Only packs referenced by cards carry &object so far. The leftover
; `&texture.<sym>` LUTs are transitional (manifest textures are numeric now;
; pending the specific-icon decision).

<asset>
  ::pine>
    @define>
      $manifest::conifer &object set
      256 &size set
      80 100 &scale range
      50 75 &anchor vec2

  ::stone>
    @define>
      $manifest::stone &object set
      128 &size set
      50 80 &scale range

  ::berry>
    @define>
      $manifest::berry &object set
      128 &size set
      50 60 &scale range

  ::flora>
    @define>
      $manifest::flora &object set
      128 &size set
      50 80 &scale range

  ::soul>
    @define>
      $manifest::soul_blue &object set   ; FLAG which soul variant — player soul (blue bg)?
      256 &size set

  ::soul_white>
    @define>
      $manifest::soul_white &object set
      256 &size set

  ::soul_offline>
    @define>
      $manifest::soul_offline &object set
      256 &size set

  ::requisite>
    @define>
      $manifest::requisite &object set
      128 &size set
      1 &texture.log set
      2 &texture.stone set
      3 &texture.food set
      7 &texture.axe set
      8 &texture.pickaxe set
      12 &texture.dust set
      13 &texture.stick set
      18 &texture.reliquary set

  ::dust>
    @define>
      128 &size set

  ::reliquary>
    @define>
      128 &size set

  ::nd_furnace>
    @define>
      $manifest::building &object set   ; FLAG nd_furnace lives in the building pack — needs a texture pick
      256 &size set

  ::workbench>
    @define>
      $manifest::building &object set   ; FLAG workbench lives in the building pack — needs a texture pick
      256 &size set

  ::blueprint>
    @define>
      $manifest::blueprint &object set
      128 &size set
      1 &texture.nd_furnace set

  ::alter>
    @define>
      $manifest::alter &object set
      256 &size set
      50 75 &anchor vec2

  ::table_slab>
    @define>
      $manifest::table_slab &object set
      128 &size set

  ::fountain>
    @define>
      $manifest::fountain &object set
      128 &size set
      1 &texture.anima set
      2 &texture.aether set

  ::concrete>
    @define>
      $manifest::concrete &object set
      256 &size set

  ::symbols>
    @define>
      $manifest::symbols &object set
      128 &size set
      5 &texture.anima set
      6 &texture.sollertia set
      7 &texture.corpus set
      8 &texture.aether set
