/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const allBlueprints: () => [number, number, number];
export const allTextures: () => [number, number, number];
export const aspectIdByName: (a: number, b: number) => [number, number, number];
export const aspectInfo: (a: number) => [number, number, number];
export const blueprintById: (a: number) => [number, number, number];
export const blueprintByKey: (a: number, b: number) => [number, number, number];
export const cardFlagBit: (a: number, b: number) => [number, number, number];
export const cardFlagFieldValue: (a: number, b: number, c: number) => [number, number, number];
export const cardLabel: (a: number, b: number, c: number) => [number, number, number, number];
export const cardTypeId: (a: number, b: number) => [number, number, number];
export const decodeDefinition: (a: number) => [number, number, number];
export const findPackedByKey: (a: number, b: number) => [number, number, number];
export const inventoryLayer: () => number;
export const isHexType: (a: number) => [number, number, number];
export const isStackLayout: (a: number, b: number) => number;
export const miniZoneLayer: () => number;
export const packDefinition: (a: number, b: number) => number;
export const packMacroZone: (a: number, b: number) => number;
export const packMicroZone: (a: number, b: number, c: number) => number;
export const packSlotMicroZone: (a: number) => number;
export const packStackMicroZone: (a: number, b: number, c: number) => number;
export const packValidAt: (a: bigint, b: number) => bigint;
export const packZoneDefinition: (a: number) => number;
export const pocketDimensionLayer: () => number;
export const recipeById: (a: number) => [number, number, number];
export const recipeByKey: (a: number, b: number) => [number, number, number];
export const recipesAll: () => [number, number, number];
export const starterBlueprintsForSoul: (a: number, b: number) => [number, number, number, number];
export const starterPacksForSoul: (a: number, b: number) => [number, number, number];
export const traitValue: (a: number, b: number, c: number) => [number, number, number];
export const unpackDefinition: (a: number) => [number, number, number];
export const unpackMacroZone: (a: number) => [number, number, number];
export const unpackMicroZone: (a: number) => [number, number, number];
export const unpackStackMicroZone: (a: number) => [number, number, number];
export const unpackZoneDefinition: (a: number) => number;
export const validAtTime: (a: bigint) => bigint;
export const worldLayer: () => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
